# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  # Corne-42 GLP nice!view Firmware
  - keyboard: Corne 42 GLP nice!view
    board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_gem
    cmake-args: -DEXTRA_CONF_FILE=../../config/corne_glp.conf
    artifact-name: corne-42-glp-niceview-left
  - keyboard: Corne 42 GLP nice!view
    board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_gem
    cmake-args: -DEXTRA_CONF_FILE=../../config/corne_glp.conf
    artifact-name: corne-42-glp-niceview-right
  - keyboard: Corne 42 GLP nice!view
    board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne-42-glp-niceview-settings-reset

  # Corne-42 Choc nice!view Firmware
  - keyboard: Corne 42 Choc nice!view
    board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_gem
    cmake-args: -DEXTRA_CONF_FILE=../../config/corne_choc.conf
    artifact-name: corne-42-choc-niceview-left
  - keyboard: Corne 42 Choc nice!view
    board: nice_nano_v2
    shield: corne_right nice_view_adapter
    cmake-args: -DEXTRA_CONF_FILE=../../config/corne_choc.conf
    artifact-name: corne-42-choc-niceview-right
  - keyboard: Corne 42 Choc nice!view
    board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne-42-choc-niceview-settings-reset

  # Chocofi nice!view Firmware
  # - keyboard: Chocofi nice!view
  #   board: nice_nano_v2
  #   shield: corne_left nice_view_adapter nice_view
  #   cmake-args: -DEXTRA_CONF_FILE=../../config/chocofi.conf
  #   artifact-name: chochofi-niceview-left
  # - keyboard: Chocofi nice!view
  #   board: nice_nano_v2
  #   shield: corne_right nice_view_adapter nice_view
  #   cmake-args: -DEXTRA_CONF_FILE=../../config/chocofi.conf
  #   artifact-name: chocofi-niceview-right
  # - keyboard: Chocofi nice!view
  #   board: nice_nano_v2
  #   shield: settings_reset
  #   artifact-name: chocofi-niceview-settings-reset
    
  # - board: nice_nano_v2
  #   shield: corne_left nice_view_adapter nice_view
  #   # snippet: studio-rpc-usb-uart
  #   # cmake-args: -DCONFIG_ZMK_STUDIO=y
  # - board: nice_nano_v2
  #   shield: corne_right nice_view_adapter nice_view
